### ISSUE TITLE
runtime: bad pointer in frame main.main at 0xc0000edb98: 0x1  

### ISSUE THREAD

**Issue by alienflash01** [NVIDIA/gpu-monitoring-tools#11]
hi,
When I use the `bindings/go/samples/dcgm/deviceInfo` file to get information about a process， I get the following error
```
runtime: bad pointer in frame main.main at 0xc0000edb98: 0x1  
fatal error: invalid pointer found on stack
````
but when I use the `dcgmi stats --pid 22574 -v ` ,I can get the correct result.

I am using cuda8 and the GPU device information is as follows:
```
Driver Version         : 390.12
DCGMSupported          : Yes
UUID                   : GPU-fe260d42-a1b6-2e82-5e69-c1029b1bef56
Brand                  : Tesla
Model                  : Tesla M40 24GB
```

**Comment by alienflash01** [comment]
All error messages are as follows
```
runtime: bad pointer in frame main.main at 0xc0000ebb98: 0x1
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw(0x5605cb, 0x1e)
	~/.local/go/src/runtime/panic.go:608 +0x72 fp=0x7fff4e6fca88 sp=0x7fff4e6fca58 pc=0x42bf52
runtime.adjustpointers(0xc0000ebb60, 0x7fff4e6fcb40, 0x7fff4e6fcf00, 0x653168, 0x864ee0)
	~/.local/go/src/runtime/stack.go:591 +0x221 fp=0x7fff4e6fcae8 sp=0x7fff4e6fca88 pc=0x442b21
runtime.adjustframe(0x7fff4e6fce10, 0x7fff4e6fcf00, 0x864ee0)
	~/.local/go/src/runtime/stack.go:633 +0x188 fp=0x7fff4e6fcb70 sp=0x7fff4e6fcae8 pc=0x442cb8
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000300, 0x0, 0x0, 0x7fffffff, 0x564f80, 0x7fff4e6fcf00, 0x0, ...)
	~/.local/go/src/runtime/traceback.go:325 +0x1326 fp=0x7fff4e6fce78 sp=0x7fff4e6fcb70 pc=0x44ce86
runtime.copystack(0xc000000300, 0x2000, 0x7fff4e6fd001)
	~/.local/go/src/runtime/stack.go:845 +0x26e fp=0x7fff4e6fd030 sp=0x7fff4e6fce78 pc=0x44336e
runtime.newstack()
	~/.local/go/src/runtime/stack.go:1017 +0x312 fp=0x7fff4e6fd1c8 sp=0x7fff4e6fd030 pc=0x443782
runtime.morestack()
	~/.local/go/src/runtime/asm_amd64.s:429 +0x8f fp=0x7fff4e6fd1d0 sp=0x7fff4e6fd1c8 pc=0x455e1f

goroutine 1 [copystack]:
time.readFile(0xc0000160d0, 0xf, 0x5, 0x55ad4a, 0x1, 0x55bb38, 0x9)
	~/.local/go/src/time/zoneinfo_read.go:412 +0x376 fp=0xc0000eb6a8 sp=0xc0000eb6a0 pc=0x486e16
time.loadTzinfoFromDirOrZip(0x55b0d5, 0x5, 0x55bb38, 0x9, 0xc000022070, 0xc000022000, 0xc00008f7b0, 0xd9bab048, 0xa91d86cf8abac403)
	~/.local/go/src/time/zoneinfo_read.go:233 +0x82 fp=0xc0000eb700 sp=0xc0000eb6a8 pc=0x485602
time.loadTzinfo(0x55bb38, 0x9, 0x55b0d5, 0x5, 0x5652a0, 0x88d270, 0xc00008f7a0, 0xc00008f7d0, 0x46e898)
	~/.local/go/src/time/zoneinfo_read.go:383 +0x8f fp=0xc0000eb758 sp=0xc0000eb700 pc=0x48672f
time.loadLocation(0x55bb38, 0x9, 0xc0000eb820, 0x1, 0x1, 0x42acb2, 0xc0000a4170, 0xc00008f850)
	~/.local/go/src/time/zoneinfo_read.go:392 +0x9d fp=0xc0000eb7e0 sp=0xc0000eb758 pc=0x4868ad
time.initLocal()
	~/.local/go/src/time/zoneinfo_unix.go:37 +0x1a8 fp=0xc0000eb840 sp=0xc0000eb7e0 pc=0x486fc8
sync.(*Once).Do(0x88d278, 0x565408)
	~/.local/go/src/sync/once.go:44 +0xb3 fp=0xc0000eb870 sp=0xc0000eb840 pc=0x46c543
time.(*Location).get(0x870e80, 0x3)
	~/.local/go/src/time/zoneinfo.go:79 +0x5e fp=0xc0000eb890 sp=0xc0000eb870 pc=0x483c6e
time.Time.abs(0xbed9bd427168e165, 0xf6d9705, 0x870e80, 0xc0000e4040)
	~/.local/go/src/time/time.go:452 +0x40 fp=0xc0000eb8e0 sp=0xc0000eb890 pc=0x4804b0
time.Time.date(0xbed9bd427168e165, 0xf6d9705, 0x870e80, 0x564401, 0x58, 0x0, 0x0, 0xc00008f9f0)
	~/.local/go/src/time/time.go:947 +0x3f fp=0xc0000eb920 sp=0xc0000eb8e0 pc=0x481bcf
time.Time.Date(0xbed9bd427168e165, 0xf6d9705, 0x870e80, 0xc0000a80c0, 0xc000000300, 0xc0000a40c0)
	~/.local/go/src/time/time.go:492 +0x44 fp=0xc0000eb970 sp=0xc0000eb920 pc=0x480704
log.(*Logger).formatHeader(0xc0000d2000, 0xc0000d2030, 0xbed9bd427168e165, 0xf6d9705, 0x870e80, 0x0, 0x0, 0x0)
	~/.local/go/src/log/log.go:103 +0x7a3 fp=0xc0000eba18 sp=0xc0000eb970 pc=0x4d2073
log.(*Logger).Output(0xc0000d2000, 0x2, 0xc0000c0180, 0x59, 0x0, 0x0)
	~/.local/go/src/log/log.go:167 +0x110 fp=0xc0000ebac8 sp=0xc0000eba18 pc=0x4d2470
log.Println(0xc00008fbd0, 0x1, 0x1)
	~/.local/go/src/log/log.go:301 +0x6c fp=0xc0000ebb08 sp=0xc0000ebac8 pc=0x4d305c
main.main()
	~/work/gpu-monitoring-tools/bindings/go/samples/dcgm/processInfo/main.go:76 +0x1ca fp=0xc0000ebf98 sp=0xc0000ebb08 pc=0x50bafa
runtime.main()
	~/.local/go/src/runtime/proc.go:201 +0x207 fp=0xc0000ebfe0 sp=0xc0000ebf98 pc=0x42d8c7
runtime.goexit()
	~/.local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000ebfe8 sp=0xc0000ebfe0 pc=0x457db1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5651c0, 0x870b70, 0x1410, 0x1)
	~/.local/go/src/runtime/proc.go:302 +0xeb fp=0xc00007cf80 sp=0xc00007cf60 pc=0x42dcbb
runtime.goparkunlock(0x870b70, 0x1410, 0x1)
	~/.local/go/src/runtime/proc.go:308 +0x53 fp=0xc00007cfb0 sp=0xc00007cf80 pc=0x42dd63
runtime.forcegchelper()
	~/.local/go/src/runtime/proc.go:251 +0xb3 fp=0xc00007cfe0 sp=0xc00007cfb0 pc=0x42db33
runtime.goexit()
	~/.local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00007cfe8 sp=0xc00007cfe0 pc=0x457db1
created by runtime.init.4
	~/.local/go/src/runtime/proc.go:240 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x5651c0, 0x870cc0, 0x42140c, 0x1)
	~/.local/go/src/runtime/proc.go:302 +0xeb fp=0xc00007d780 sp=0xc00007d760 pc=0x42dcbb
runtime.goparkunlock(0x870cc0, 0x57140c, 0x1)
	~/.local/go/src/runtime/proc.go:308 +0x53 fp=0xc00007d7b0 sp=0xc00007d780 pc=0x42dd63
runtime.bgsweep(0xc0000a6000)
	~/.local/go/src/runtime/mgcsweep.go:52 +0x8f fp=0xc00007d7d8 sp=0xc00007d7b0 pc=0x420eaf
runtime.goexit()
	~/.local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00007d7e0 sp=0xc00007d7d8 pc=0x457db1
created by runtime.gcenable
	~/.local/go/src/runtime/mgc.go:216 +0x58

goroutine 4 [finalizer wait]:
runtime.gopark(0x5651c0, 0x88d190, 0x140f, 0x1)
	~/.local/go/src/runtime/proc.go:302 +0xeb fp=0xc00007df28 sp=0xc00007df08 pc=0x42dcbb
runtime.goparkunlock(0x88d190, 0x140f, 0x1)
	~/.local/go/src/runtime/proc.go:308 +0x53 fp=0xc00007df58 sp=0xc00007df28 pc=0x42dd63
runtime.runfinq()
	~/.local/go/src/runtime/mfinal.go:175 +0x99 fp=0xc00007dfe0 sp=0xc00007df58 pc=0x418889
runtime.goexit()
	~/.local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x457db1
created by runtime.createfing
	~/.local/go/src/runtime/mfinal.go:156 +0x61

```

**Comment by alienflash01** [comment]
I debugged the program and found that if I comment out `log.Println("Enabling DCGM watches to start collecting process stats. This may take a few seconds....")`, the code can give the correct result. And when tested the `log` package in other code, for example adding the same `log` code in the `go/samples/dcgm/deviceInfo` file, I didn't reproduce the problem.
My go version is `go version go1.11 linux/amd64` and  the Linux kernel is `3.18.6-2.el7.centos.x86_64`、centos7.

**Comment by flx42** [comment]
@alienflash01 what's your version of DCGM?

**Comment by alienflash01** [comment]
@flx42  `dcgmi  version: 1.4.2`

**Comment by guptaNswati** [comment]
@alienflash01 looks like this issue is resolved on your end, so closing it. Also I would suggest updating DCGM to its current 1.4.6 version.
