### ISSUE TITLE
Get GPU busid failed by changing default metric csv

### ISSUE THREAD

**Issue by pokerfaceSad** [NVIDIA/gpu-monitoring-tools#118]
I changed `etc/dcgm-exporter/default-counters.csv` following the [README#changing-metrics](https://github.com/NVIDIA/gpu-monitoring-tools/#changing-metrics) to
```
# Format,,
# If line starts with a '#' it is considered a comment,,
# DCGM FIELD, Prometheus metric type, help message

DCGM_FI_DEV_GPU_UTIL,      gauge, GPU utilization (in %).
DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).
DCGM_FI_DEV_PCI_BUSID,     counter, PCI attributes for the device
```
And start the dcgm container by `docker run --cap-add SYS_ADMIN -it --rm -v $PWD/dcgm-exporter:/etc/dcgm-exporter -p 9400:9400 nvidia/dcgm-expoer:2.0.13-2.1.0-ubuntu20.04`

But it panic and exit.
```
INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Pipeline starting
INFO[0000] Starting webserver
panic: runtime error: growslice: cap out of range [recovered]
        panic: runtime error: growslice: cap out of range

goroutine 34 [running]:
text/template.errRecover(0xc000291d48)
        /usr/local/go/src/text/template/exec.go:164 +0x1cb
panic(0x9ba6a0, 0xb27970)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
fmt.(*buffer).writeString(...)
        /usr/local/go/src/fmt/print.go:82
fmt.(*fmt).padString(0xc0001fa1e0, 0x3030303030303030, 0x302e30303a32303a)
        /usr/local/go/src/fmt/format.go:110 +0xf3
fmt.(*fmt).fmtS(0xc0001fa1e0, 0x3030303030303030, 0x302e30303a32303a)
        /usr/local/go/src/fmt/format.go:359 +0x61
fmt.(*pp).fmtString(0xc0001fa1a0, 0x3030303030303030, 0x302e30303a32303a, 0x76)
        /usr/local/go/src/fmt/print.go:447 +0x131
fmt.(*pp).printArg(0xc0001fa1a0, 0x986de0, 0xc0001ee450, 0x76)
        /usr/local/go/src/fmt/print.go:698 +0x877
fmt.(*pp).doPrint(0xc0001fa1a0, 0xc000291508, 0x1, 0x1)
        /usr/local/go/src/fmt/print.go:1161 +0xf8
fmt.Fprint(0xb31aa0, 0xc0001d4ed0, 0xc000291508, 0x1, 0x1, 0x986d01, 0xc0001ea220, 0x0)
        /usr/local/go/src/fmt/print.go:232 +0x58
text/template.(*state).printValue(0xc000291cc8, 0xb40840, 0xc0002064b0, 0x986de0, 0xc0001ea220, 0x198)
        /usr/local/go/src/text/template/exec.go:953 +0xe4
text/template.(*state).walk(0xc000291cc8, 0xa27d60, 0xc0001ea210, 0x199, 0xb40840, 0xc0002064b0)
        /usr/local/go/src/text/template/exec.go:260 +0x4ef
text/template.(*state).walk(0xc000291cc8, 0xa27d60, 0xc0001ea210, 0x199, 0xb40a80, 0xc0001d4990)
        /usr/local/go/src/text/template/exec.go:266 +0x142
text/template.(*state).walkRange.func1(0x986020, 0xc0001de570, 0x82, 0xa27d60, 0xc0001ea210, 0x199)
        /usr/local/go/src/text/template/exec.go:353 +0x124
text/template.(*state).walkRange(0xc000291cc8, 0x97bd80, 0xc0001d6660, 0x197, 0xc00020c140)
        /usr/local/go/src/text/template/exec.go:362 +0x517
text/template.(*state).walk(0xc000291cc8, 0x97bd80, 0xc0001d6660, 0x197, 0xb40b80, 0xc00020c140)
        /usr/local/go/src/text/template/exec.go:269 +0x43d
text/template.(*state).walk(0xc000291cc8, 0x97bd80, 0xc0001d6660, 0x197, 0xb40a80, 0xc0001d48d0)
        /usr/local/go/src/text/template/exec.go:266 +0x142
text/template.(*state).walkRange.func1(0x986020, 0xf3c0a0, 0x82, 0x97bd80, 0xc0001d6660, 0x197)
        /usr/local/go/src/text/template/exec.go:353 +0x124
text/template.(*state).walkRange(0xc000291cc8, 0x979900, 0xc0001e44a0, 0x97, 0xc00020c180)
        /usr/local/go/src/text/template/exec.go:362 +0x517
text/template.(*state).walk(0xc000291cc8, 0x979900, 0xc0001e44a0, 0x97, 0xb40b80, 0xc00020c180)
        /usr/local/go/src/text/template/exec.go:269 +0x43d
text/template.(*state).walk(0xc000291cc8, 0x979900, 0xc0001e44a0, 0x97, 0xb40a80, 0xc0001d4810)
        /usr/local/go/src/text/template/exec.go:266 +0x142
text/template.(*Template).execute(0xc0001ec200, 0xb31aa0, 0xc0001d4ed0, 0x979900, 0xc0001e44a0, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:221 +0x20a
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:204
main.FormatMetrics(0xc000202000, 0x119, 0xc0001ec200, 0xc0001d6660, 0x4, 0x4, 0x1, 0x1, 0x0, 0xc0001d6228)
        /go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/pipeline.go:182 +0xa3
main.(*MetricsPipeline).run(0xc00020c1c0, 0xc000177eb0, 0x2, 0x1, 0x1)
        /go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/pipeline.go:126 +0x202
main.(*MetricsPipeline).Run(0xc00020c1c0, 0xc0001d6000, 0xc00022e000, 0xc0002042a0)
        /go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/pipeline.go:98 +0x1e4
created by main.Run
        /go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/main.go:123 +0x39c
```
But it works well when I change the `DCGM_FI_DEV_PCI_BUSID` to another metric like `DCGM_FI_DEV_PCI_COMBINED_ID`

**Comment by pokerfaceSad** [comment]
It has been 3 weeks.
Anyone can help me?
@RenaudWasTaken
